[build]
  publish = "website"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/account"
  to = "/account.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

[[redirects]]
  from = "/upgrade"
  to = "/upgrade.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200





























