/** Keyword lists for Trades group. Each title is a Wikipedia article. */

function kw(title, ...aliases) {
  return [title, aliases.length ? aliases : [title.toLowerCase()]];
}

export const TRADES_SUBJECT_KEYWORDS = Object.freeze({
  'Blue-collar worker': [
    kw('Skilled worker'),
    kw('Tradesman', 'skilled trades'),
    kw('Apprenticeship'),
    kw('Journeyman'),
    kw('Vocational education', 'trade school'),
    kw('Laborer'),
    kw('Shift work'),
    kw('Manual labour', 'manual labor'),
  ],
  'Skilled worker': [
    kw('Apprenticeship'),
    kw('Journeyman'),
    kw('Vocational education', 'trade school'),
    kw('Tradesman', 'skilled trades'),
    kw('Certification'),
    kw('Blue-collar worker'),
    kw('Manufacturing'),
    kw('Craftsmanship', 'craft worker'),
  ],
  Tradesman: [
    kw('Apprenticeship'),
    kw('Journeyman'),
    kw('Master craftsman', 'master tradesman'),
    kw('Guild'),
    kw('Vocational education', 'trade school'),
    kw('Union shop', 'closed shop'),
    kw('Blue-collar worker'),
    kw('Skilled worker'),
  ],
  Apprenticeship: [
    kw('Journeyman'),
    kw('Mentorship', 'mentor'),
    kw('On-the-job training', 'ojt'),
    kw('Vocational education', 'trade school'),
    kw('Registered Apprenticeship', 'us apprenticeship program'),
    kw('Pre-apprenticeship', 'pre-apprenticeship program'),
    kw('Trade union'),
    kw('Competency-based learning', 'competency model'),
  ],
  Journeyman: [
    kw('Apprenticeship'),
    kw('Master craftsman', 'master license'),
    kw('Journeyman electrician', 'journeyman license'),
    kw('Trade union'),
    kw('Licensing', 'trade license'),
    kw('Continuing education'),
    kw('Prevailing wage'),
    kw('Skilled worker'),
  ],
  'Vocational education': [
    kw('Career and technical education', 'cte'),
    kw('Community college'),
    kw('Apprenticeship'),
    kw('Trade school', 'technical school'),
    kw('Certification'),
    kw('Workforce development'),
    kw('Cooperative education', 'co-op'),
    kw('Adult education'),
  ],
  'Career and technical education': [
    kw('Vocational education', 'trade school'),
    kw('Perkins Act', 'carl perkins act'),
    kw('Workforce Innovation and Opportunity Act', 'wioa'),
    kw('Community college'),
    kw('Apprenticeship'),
    kw('STEM education', 'stem pathways'),
    kw('Dual enrollment'),
    kw('Industry-recognized credential', 'industry credential'),
  ],
  Electrician: [
    kw('National Electrical Code', 'nec'),
    kw('Electrical wiring'),
    kw('Circuit breaker'),
    kw('Journeyman electrician', 'journeyman license'),
    kw('Master electrician', 'master electrician license'),
    kw('Lockout–tagout', 'lockout tagout'),
    kw('Multimeter'),
    kw('Apprenticeship'),
  ],
  Plumbing: [
    kw('Plumber'),
    kw('Pipefitter'),
    kw('Water heater'),
    kw('Drain (plumbing)', 'drain cleaning'),
    kw('Sump pump'),
    kw('Backflow prevention', 'backflow preventer'),
    kw('Apprenticeship'),
    kw('Uniform Plumbing Code', 'plumbing code'),
  ],
  Welding: [
    kw('Gas metal arc welding', 'mig welding'),
    kw('Shielded metal arc welding', 'stick welding'),
    kw('Gas tungsten arc welding', 'tig welding'),
    kw('Welding helmet', 'welding hood'),
    kw('American Welding Society', 'aws certification'),
    kw('Pipe welding', 'pipe welder'),
    kw('Oxy-fuel welding and cutting', 'oxyfuel cutting'),
    kw('Welding defect', 'weld inspection'),
  ],
  'Gas metal arc welding': [
    kw('Welding'),
    kw('Shielded metal arc welding', 'stick welding'),
    kw('Gas tungsten arc welding', 'tig welding'),
    kw('Welding power supply', 'welder machine'),
    kw('Shielding gas'),
    kw('Wire feed welding', 'flux core vs mig'),
    kw('Welding helmet', 'auto darkening helmet'),
    kw('American Welding Society', 'aws d1.1'),
  ],
  'Shielded metal arc welding': [
    kw('Welding'),
    kw('Gas metal arc welding', 'mig welding'),
    kw('Electrode', 'welding rod'),
    kw('Welding power supply'),
    kw('Pipeline welding', 'pipeline welder'),
    kw('American Welding Society', 'aws certification'),
    kw('Welding helmet'),
    kw('Arc welding', 'arc flash safety'),
  ],
  Carpentry: [
    kw('Framing (construction)', 'house framing'),
    kw('Joinery'),
    kw('Cabinetry', 'cabinet making'),
    kw('Rough carpentry', 'rough framing'),
    kw('Finish carpentry', 'trim carpentry'),
    kw('Circular saw'),
    kw('Building code'),
    kw('Apprenticeship'),
  ],
  HVAC: [
    kw('Refrigeration'),
    kw('Air conditioning'),
    kw('Furnace (central heating)', 'furnace'),
    kw('Heat pump'),
    kw('Thermostat'),
    kw('Duct (flow)', 'ductwork'),
    kw('Refrigerant'),
    kw('EPA Section 608 certification', 'epa 608'),
  ],
  Masonry: [
    kw('Brickwork', 'bricklaying'),
    kw('Concrete masonry unit', 'cinder block'),
    kw('Mortar (masonry)', 'mortar mix'),
    kw('Tuckpointing'),
    kw('Stone masonry', 'stonemason'),
    kw('Chimney'),
    kw('Retaining wall'),
    kw('Apprenticeship'),
  ],
  Construction: [
    kw('Construction management'),
    kw('General contractor'),
    kw('Building code'),
    kw('Blueprint', 'construction drawings'),
    kw('Construction site safety', 'jobsite safety'),
    kw('Scaffolding'),
    kw('Heavy equipment'),
    kw('Project management'),
  ],
  'Construction management': [
    kw('General contractor'),
    kw('Construction estimating', 'cost estimating'),
    kw('Critical path method', 'cpm schedule'),
    kw('Building information modeling', 'bim'),
    kw('Construction contract', 'aia contract'),
    kw('Jobsite superintendent', 'superintendent'),
    kw('Safety management', 'osha construction'),
    kw('Project management'),
  ],
  'Heavy equipment': [
    kw('Excavator'),
    kw('Bulldozer'),
    kw('Backhoe', 'backhoe loader'),
    kw('Crane (machine)', 'crane operator'),
    kw('Forklift'),
    kw('Skid-steer loader', 'skid steer'),
    kw('Heavy equipment operator', 'operator certification'),
    kw('Preventive maintenance', 'equipment maintenance'),
  ],
  "Commercial driver's license": [
    kw('Truck driver'),
    kw('ELD mandate', 'electronic logging device'),
    kw('Hours of service'),
    kw('Pre-trip inspection', 'vehicle inspection'),
    kw('Air brake (road vehicle)', 'air brakes endorsement'),
    kw('Hazmat endorsement', 'hazmat cdl'),
    kw('Tanker endorsement', 'tanker cdl'),
    kw('CDL training school', 'truck driving school'),
  ],
  'Truck driver': [
    kw("Commercial driver's license", 'cdl'),
    kw('Hours of service'),
    kw('Truck stop'),
    kw('Less-than-truckload shipping', 'ltl freight'),
    kw('Logistics'),
    kw('Supply chain'),
    kw('Owner-operator', 'owner operator trucking'),
    kw('Dispatcher (trucking)', 'dispatch'),
  ],
  'Auto mechanic': [
    kw('Automotive repair', 'car repair'),
    kw('OBD-II', 'obd2 scanner'),
    kw('Brake pad', 'brake service'),
    kw('ASE certification', 'ase certified'),
    kw('Oil change'),
    kw('Transmission (mechanical)', 'transmission repair'),
    kw('Wheel alignment', 'alignment service'),
    kw('Preventive maintenance', 'scheduled maintenance'),
  ],
  'Diesel engine': [
    kw('Diesel mechanic', 'diesel technician'),
    kw('Turbocharger'),
    kw('Fuel injection'),
    kw('Glowplug', 'glow plug'),
    kw('Exhaust gas recirculation', 'egr system'),
    kw('Diesel particulate filter', 'dpf filter'),
    kw('Preventive maintenance', 'fleet maintenance'),
    kw('Heavy equipment'),
  ],
  Machinist: [
    kw('Numerical control', 'cnc machining'),
    kw('Lathe'),
    kw('Milling machine', 'mill machine'),
    kw('Calipers', 'micrometer measurement'),
    kw('Blueprint reading', 'technical drawing'),
    kw('Cutting tool (machining)', 'tooling'),
    kw('Apprenticeship'),
    kw('Manufacturing'),
  ],
  'Numerical control': [
    kw('CNC router', 'cnc machine'),
    kw('G-code'),
    kw('Machinist'),
    kw('Computer-aided manufacturing', 'cam software'),
    kw('Lathe'),
    kw('Milling machine'),
    kw('Toolpath', 'cnc programming'),
    kw('Manufacturing'),
  ],
  Pipefitter: [
    kw('Plumbing'),
    kw('Pipe welding', 'welding pipe'),
    kw('Flange'),
    kw('Valve'),
    kw('Blueprint reading', 'isometric drawing'),
    kw('Apprenticeship'),
    kw('Pressure testing', 'hydrotest'),
    kw('Industrial maintenance', 'plant maintenance'),
  ],
  Ironworker: [
    kw('Structural steel'),
    kw('Reinforcing bar', 'rebar'),
    kw('Welding'),
    kw('Riveting', 'structural rivet'),
    kw('Crane (machine)', 'crane signaling'),
    kw('Fall protection', 'harness safety'),
    kw('Apprenticeship'),
    kw('Construction'),
  ],
  Roofing: [
    kw('Asphalt shingle'),
    kw('Metal roof', 'standing seam'),
    kw('Flat roof', 'membrane roofing'),
    kw('Flashing (weatherproofing)', 'roof flashing'),
    kw('Gutter'),
    kw('Roof leak repair', 'leak detection'),
    kw('Fall protection', 'roof safety'),
    kw('Building envelope', 'weatherproofing'),
  ],
  Drywall: [
    kw('Joint compound', 'mudding drywall'),
    kw('Taping (drywall)', 'drywall tape'),
    kw('Texture painting', 'orange peel texture'),
    kw('Stud finder', 'framing layout'),
    kw('Sanding', 'pole sander'),
    kw('Plaster'),
    kw('Finish carpentry', 'trim work'),
    kw('Remodeling', 'home renovation'),
  ],
  Concrete: [
    kw('Cement'),
    kw('Reinforced concrete', 'rebar concrete'),
    kw('Formwork'),
    kw('Concrete slab', 'slab finishing'),
    kw('Curing (concrete)', 'concrete curing'),
    kw('Stamped concrete', 'decorative concrete'),
    kw('Sidewalk construction', 'flatwork'),
    kw('Ready-mix concrete', 'concrete truck'),
  ],
  Landscaping: [
    kw('Lawn care', 'turf management'),
    kw('Irrigation sprinkler', 'sprinkler system'),
    kw('Pruning'),
    kw('Mulch'),
    kw('Landscape design'),
    kw('Hardscaping', 'pavers patio'),
    kw('Pesticide application', 'pest control license'),
    kw('Small business management', 'landscaping business'),
  ],
  Arborist: [
    kw('Tree pruning', 'pruning'),
    kw('Chainsaw safety', 'chainsaw'),
    kw('Tree risk assessment', 'hazard tree'),
    kw('International Society of Arboriculture', 'isa certification'),
    kw('Climbing arborist', 'tree climbing'),
    kw('Stump grinding', 'stump removal'),
    kw('Urban forestry'),
    kw('Plant health care', 'tree health'),
  ],
  Lineworker: [
    kw('Electric power distribution', 'power lines'),
    kw('Utility pole'),
    kw('Bucket truck', 'aerial lift'),
    kw('High-voltage cable', 'high voltage safety'),
    kw('Electrical substation'),
    kw('Outage restoration', 'storm restoration'),
    kw('Climbing spikes', 'pole climbing'),
    kw('Apprenticeship'),
  ],
  Millwright: [
    kw('Industrial maintenance', 'plant mechanic'),
    kw('Bearing (mechanical)', 'bearing replacement'),
    kw('Conveyor system'),
    kw('Precision alignment', 'laser alignment'),
    kw('Hydraulics'),
    kw('Pneumatics'),
    kw('Blueprint reading', 'machinery installation'),
    kw('Manufacturing'),
  ],
  Boilermaker: [
    kw('Boiler'),
    kw('Pressure vessel'),
    kw('Welding'),
    kw('Tube replacement', 'boiler tubes'),
    kw('Refractory'),
    kw('Confined space', 'confined space entry'),
    kw('Apprenticeship'),
    kw('Power plant', 'plant shutdown work'),
  ],
  'Sheet metal': [
    kw('Duct (flow)', 'duct fabrication'),
    kw('HVAC'),
    kw('Brake (sheet metal bending)', 'sheet metal brake'),
    kw('Soldering'),
    kw('Roof flashing', 'flashing fabrication'),
    kw('Apprenticeship'),
    kw('Blueprint reading', 'shop drawings'),
    kw('Welding'),
  ],
  Refrigeration: [
    kw('HVAC'),
    kw('Refrigerant'),
    kw('Compressor'),
    kw('Evaporator', 'evaporator coil'),
    kw('Condenser (heat transfer)', 'condenser coil'),
    kw('EPA Section 608 certification', 'epa 608'),
    kw('Supermarket refrigeration', 'rack refrigeration'),
    kw('Preventive maintenance', 'service technician'),
  ],
  'House painter and decorator': [
    kw('Interior painting', 'house painting'),
    kw('Exterior painting', 'exterior prep'),
    kw('Primer (paint)', 'paint primer'),
    kw('Caulking'),
    kw('Drywall repair', 'patch and paint'),
    kw('Color theory', 'paint colors'),
    kw('Lead paint abatement', 'lead safe practices'),
    kw('Small business management', 'painting business'),
  ],
  Glazier: [
    kw('Glass installation', 'window glass'),
    kw('Curtain wall (architecture)', 'curtain wall'),
    kw('Insulated glazing', 'double pane window'),
    kw('Storefront glass', 'commercial glazing'),
    kw('Caulking'),
    kw('Blueprint reading', 'glass shop drawings'),
    kw('Apprenticeship'),
    kw('Construction'),
  ],
  Locksmithing: [
    kw('Lock (security device)', 'door lock'),
    kw('Key cutting', 'key duplication'),
    kw('Rekeying', 'lock rekey'),
    kw('Deadbolt'),
    kw('Master key', 'master key system'),
    kw('Safe cracking', 'safe opening'),
    kw('Access control'),
    kw('Small business management', 'locksmith business'),
  ],
  Mechatronics: [
    kw('Robotics'),
    kw('Programmable logic controller', 'plc programming'),
    kw('Sensors'),
    kw('Actuator'),
    kw('Industrial automation', 'factory automation'),
    kw('Control system'),
    kw('Instrumentation'),
    kw('Manufacturing'),
  ],
  Instrumentation: [
    kw('Programmable logic controller', 'plc'),
    kw('Calibration'),
    kw('Pressure measurement', 'pressure transmitter'),
    kw('Temperature measurement', 'rtd thermocouple'),
    kw('Control valve'),
    kw('Distributed control system', 'dcs'),
    kw('Loop checking', 'instrument loop'),
    kw('Industrial maintenance', 'plant instrument tech'),
  ],
  Manufacturing: [
    kw('Lean manufacturing'),
    kw('Six Sigma', 'lean six sigma'),
    kw('Quality control'),
    kw('Assembly line'),
    kw('Supply chain management', 'supply chain'),
    kw('Inventory management'),
    kw('Preventive maintenance', 'tpm maintenance'),
    kw('Automation'),
  ],
  'Occupational safety and health': [
    kw('Occupational Safety and Health Administration', 'osha'),
    kw('Hazard communication', 'hazcom training'),
    kw('Personal protective equipment', 'ppe'),
    kw('Job safety analysis', 'jsa form'),
    kw('Incident investigation', 'root cause analysis'),
    kw('Safety culture'),
    kw('Workers compensation', 'workers comp'),
    kw('Industrial hygiene'),
  ],
  'Occupational Safety and Health Administration': [
    kw('OSHA 10-hour training', 'osha 10'),
    kw('OSHA 30-hour training', 'osha 30'),
    kw('General duty clause', 'osha general duty'),
    kw('Fall protection'),
    kw('Hazard communication standard', 'ghs labels'),
    kw('Construction safety', 'osha construction standard'),
    kw('Whistleblower protection', 'osha complaint'),
    kw('Occupational safety and health'),
  ],
  'National Electrical Code': [
    kw('Electrical wiring'),
    kw('Ground fault circuit interrupter', 'gfci'),
    kw('Arc-fault circuit interrupter', 'afci'),
    kw('Circuit breaker panel', 'breaker box'),
    kw('Conduit (electrical)', 'electrical conduit'),
    kw('Electrician'),
    kw('NFPA 70E', 'arc flash standard'),
    kw('Building code'),
  ],
  'Lockout–tagout': [
    kw('Occupational safety and health'),
    kw('Confined space', 'confined space entry'),
    kw('Electrical safety', 'arc flash safety'),
    kw('Machine guarding', 'machine guard'),
    kw('Permit to work', 'work permit'),
    kw('Hazardous energy control', 'energy isolation'),
    kw('Safety training', 'osha training'),
    kw('Industrial maintenance', 'maintenance safety'),
  ],
  Forklift: [
    kw('Forklift certification', 'forklift license'),
    kw('Pallet jack'),
    kw('Warehouse'),
    kw('Loading dock'),
    kw('OSHA forklift standard', 'powered industrial trucks'),
    kw('Material handling'),
    kw('Inventory management'),
    kw('Order picker', 'order picking'),
  ],
  'Crane (machine)': [
    kw('Mobile crane', 'crane rental'),
    kw('Tower crane'),
    kw('Rigging (material handling)', 'crane rigging'),
    kw('NCCCO certification', 'crane operator certification'),
    kw('Load chart', 'crane load chart'),
    kw('Heavy equipment'),
    kw('Construction'),
    kw('OSHA crane standard', 'crane safety'),
  ],
  Warehouse: [
    kw('Inventory management'),
    kw('Forklift'),
    kw('Pick and pack', 'order fulfillment'),
    kw('Pallet racking', 'warehouse racking'),
    kw('Barcode scanner', 'barcode system'),
    kw('Logistics'),
    kw('Supply chain management', 'supply chain'),
    kw('Shipping and receiving', 'receiving clerk'),
  ],
  'Personal protective equipment': [
    kw('Hard hat'),
    kw('Safety glasses'),
    kw('High-visibility clothing', 'hi-vis vest'),
    kw('Respirator'),
    kw('Hearing protection', 'ear protection'),
    kw('Fall protection', 'safety harness'),
    kw('Steel-toe boot', 'safety boots'),
    kw('Glove', 'work gloves'),
  ],
  Scaffolding: [
    kw('Fall protection'),
    kw('Ladder safety', 'extension ladder'),
    kw('Supported scaffold', 'frame scaffold'),
    kw('Suspended scaffold', 'swing stage'),
    kw('OSHA scaffold standard', 'scaffold safety'),
    kw('Construction'),
    kw('Guardrail'),
    kw('Competent person (OSHA)', 'competent person training'),
  ],
  'First aid': [
    kw('Cardiopulmonary resuscitation', 'cpr'),
    kw('Automated external defibrillator', 'aed'),
    kw('Bleeding control', 'tourniquet use'),
    kw('OSHA first aid standard', 'workplace first aid'),
    kw('First aid kit'),
    kw('Choking treatment', 'heimlich maneuver'),
    kw('Burn management', 'burn first aid'),
    kw('Emergency action plan', 'evacuation plan'),
  ],
  'Cardiopulmonary resuscitation': [
    kw('Automated external defibrillator', 'aed training'),
    kw('Basic life support', 'bls certification'),
    kw('First aid'),
    kw('Chest compressions', 'hands-only cpr'),
    kw('American Heart Association', 'aha certification'),
    kw('American Red Cross', 'red cross training'),
    kw('Choking treatment', 'heimlich maneuver'),
    kw('Emergency medical technician', 'emt training'),
  ],
  'Technical drawing': [
    kw('Blueprint reading', 'blueprint symbols'),
    kw('Computer-aided design', 'cad drafting'),
    kw('Orthographic projection'),
    kw('Dimensioning', 'tolerancing'),
    kw('Welding symbols', 'weld symbols'),
    kw('Electrical schematic', 'wiring diagram'),
    kw('Construction drawing', 'plan reading'),
    kw('Geometric dimensioning and tolerancing', 'gd&t'),
  ],
  'Trade union': [
    kw('Collective bargaining'),
    kw('Apprenticeship'),
    kw('Union steward', 'shop steward'),
    kw('Prevailing wage'),
    kw('Project labor agreement', 'pla agreement'),
    kw('Right-to-work law'),
    kw('Strike action', 'labor strike'),
    kw('AFL-CIO'),
  ],
  Laborer: [
    kw('Construction'),
    kw('Flagger (construction)', 'flagger certification'),
    kw('Concrete'),
    kw('Demolition'),
    kw('Site cleanup', 'jobsite cleanup'),
    kw('OSHA 10-hour training', 'osha 10'),
    kw('General contractor'),
    kw('Landscaping'),
  ],
  'Stationary engineer': [
    kw('Boiler operation', 'high pressure boiler'),
    kw('HVAC'),
    kw('Power plant operator', 'plant operations'),
    kw('Refrigeration'),
    kw('Building maintenance', 'facilities maintenance'),
    kw('Preventive maintenance', 'building engineer'),
    kw('NIULPE certification', 'stationary engineer license'),
    kw('Industrial maintenance', 'operating engineer'),
  ],
  'Dangerous goods': [
    kw('HAZMAT suit', 'hazmat training'),
    kw('Safety data sheet', 'sds sheets'),
    kw('Hazardous waste disposal', 'haz waste manifest'),
    kw('DOT placards', 'hazmat placards'),
    kw('Emergency Response Guidebook', 'erg guidebook'),
    kw('Spill containment', 'spill response'),
    kw('HAZWOPER training', 'hazwoper 40 hour'),
    kw('Personal protective equipment', 'ppe levels'),
  ],
});
