/** Keyword lists for Majors. Each title is a Wikipedia article. Other groups stay empty until reviewed. */

function kw(title, ...aliases) {
  return [title, aliases.length ? aliases : [title.toLowerCase()]];
}

export const MAJOR_SUBJECT_KEYWORDS = Object.freeze({
  'Pre-medical': [
    kw('Medical College Admission Test', 'mcat'),
    kw('Organic chemistry'),
    kw('Anatomy'),
    kw('Biochemistry'),
    kw('Medical school'),
    kw('Physiology'),
  ],
  'Pre-law': [
    kw('Law School Admission Test', 'lsat'),
    kw('Law school'),
    kw('Constitutional law'),
    kw('Contract'),
    kw('Tort'),
    kw('Criminal law'),
  ],
  'Pre-dental': [
    kw('Dental Admission Test', 'dat'),
    kw('Dental school'),
    kw('Tooth'),
    kw('Orthodontics'),
    kw('Periodontology'),
    kw('Oral hygiene'),
  ],
  Pharmacy: [
    kw('Pharmacology'),
    kw('Pharmaceutical drug'),
    kw('Pharmacokinetics'),
    kw('Medicinal chemistry'),
    kw('Doctor of Pharmacy'),
    kw('Over-the-counter drug'),
  ],
  'Computer science': [
    kw('Algorithm'),
    kw('Data structure', 'data structure', 'data structures'),
    kw('Computational complexity theory', 'complexity'),
    kw('Programming language'),
    kw('Compiler'),
    kw('Operating system'),
    kw('Discrete mathematics'),
    kw('Theory of computation'),
    kw('Computer program', 'program'),
    kw('Variable (computer science)', 'variable'),
    kw('Subroutine', 'function'),
    kw('Control flow'),
    kw('For loop', 'loop', 'for loop'),
    kw('Recursion (computer science)', 'recursion'),
    kw('Scope (computer science)', 'scope'),
    kw('Boolean data type', 'boolean'),
    kw('Syntax (programming languages)', 'syntax'),
    kw('Pseudocode'),
    kw('Parameter (computer programming)', 'parameter'),
    kw('Return statement', 'return'),
    kw('Conditional (computer programming)', 'conditional', 'if statement'),
    kw('Array (data structure)', 'array'),
    kw('Linked list', 'linked list'),
    kw('Stack (abstract data type)', 'stack'),
    kw('Queue (abstract data type)', 'queue'),
    kw('Tree (data structure)', 'tree'),
    kw('Binary tree', 'binary tree'),
    kw('Binary search tree', 'binary search tree', 'bst'),
    kw('Graph (abstract data type)', 'graph'),
    kw('Hash table', 'hash table', 'hash', 'hashing'),
    kw('Heap (data structure)', 'heap'),
    kw('Binary heap', 'binary heap'),
    kw('Trie', 'trie', 'prefix tree'),
    kw('Set (abstract data type)', 'set'),
    kw('Associative array', 'map', 'hash map'),
    kw('Dynamic array', 'dynamic array'),
    kw('Append', 'append'),
    kw('Binary number', 'binary', 'binary number'),
    kw('Binary code', 'binary code'),
    kw('Binary search', 'binary search'),
    kw('Bit', 'bit'),
    kw('Byte', 'byte'),
    kw('Sorting algorithm', 'sort', 'sorting'),
    kw('Search algorithm', 'search algorithm'),
    kw('Big O notation', 'big o', 'big-o', 'big o notation'),
    kw('Greedy algorithm', 'greedy'),
    kw('Dynamic programming', 'dynamic programming'),
    kw('Divide-and-conquer algorithm', 'divide and conquer', 'divide-and-conquer'),
    kw('Breadth-first search', 'breadth-first search', 'bfs'),
    kw('Depth-first search', 'depth-first search', 'dfs'),
    kw("Dijkstra's algorithm", 'dijkstra', 'dijkstras algorithm'),
    kw('Merge sort', 'merge sort'),
    kw('Quicksort', 'quicksort', 'quick sort'),
    kw('Insertion sort', 'insertion sort'),
    kw('Graph traversal', 'graph traversal'),
    kw('Central processing unit', 'cpu'),
    kw('Computer memory', 'memory', 'ram'),
    kw('Process (computing)', 'process'),
    kw('Thread (computing)', 'thread'),
    kw('Computer architecture'),
    kw('Instruction set architecture', 'instruction set'),
    kw('Machine code', 'machine code'),
    kw('Assembly language', 'assembly'),
    kw('Automata theory', 'automata'),
    kw('Turing machine', 'turing machine'),
    kw('Finite-state machine', 'finite state machine', 'fsm'),
    kw('Computability theory', 'computability'),
    kw('P versus NP problem', 'p vs np', 'p versus np'),
    kw('Boolean algebra'),
    kw('Graph theory'),
    kw('Set (mathematics)', 'set theory'),
    kw('Mathematical logic', 'logic'),
    kw('Combinatorics'),
    kw('Mathematical proof', 'proof'),
    kw('Object-oriented programming', 'oop', 'object oriented programming'),
    kw('Class (computer programming)', 'class'),
    kw('Object (computer science)', 'object'),
    kw('Encapsulation (computer programming)', 'encapsulation'),
    kw('Inheritance (object-oriented programming)', 'inheritance'),
    kw('Polymorphism (computer science)', 'polymorphism'),
    kw('Abstract data type', 'abstract data type', 'adt'),
    kw('Application programming interface', 'api'),
    kw('Debugging'),
    kw('Integrated development environment', 'ide'),
    kw('Interpreter (computing)', 'interpreter'),
    kw('Database'),
    kw('Relational database', 'relational database'),
    kw('SQL', 'sql'),
    kw('Computer network', 'network'),
    kw('Computer graphics', 'graphics'),
    kw('Human–computer interaction', 'human computer interaction', 'hci'),
    kw('Parallel computing', 'parallel computing'),
    kw('Distributed computing', 'distributed computing'),
    kw('Computer ethics', 'ethics'),
  ],
  'Software engineering': [
    kw('Software development'),
    kw('Software testing'),
    kw('Requirements engineering'),
    kw('Software design pattern', 'design pattern'),
    kw('Version control'),
    kw('Agile software development', 'agile'),
    kw('Software architecture'),
    kw('Debugging'),
  ],
  'Information technology': [
    kw('Information system'),
    kw('Computer network'),
    kw('Information security'),
    kw('Technical support'),
    kw('Database'),
    kw('Cloud computing'),
    kw('System administrator'),
    kw('ITIL', 'itil'),
  ],
  'Data science': [
    kw('Statistics'),
    kw('Machine learning'),
    kw('Data analysis'),
    kw('Data visualization'),
    kw('Big data'),
    kw('Data mining'),
    kw('Python (programming language)', 'python'),
    kw('Regression analysis'),
  ],
  'Computer security': [
    kw('Cryptography'),
    kw('Malware'),
    kw('Vulnerability (computing)', 'vulnerability'),
    kw('Authentication'),
    kw('Firewall (computing)', 'firewall'),
    kw('Penetration test'),
    kw('Encryption'),
    kw('Phishing'),
  ],
  'Artificial intelligence': [
    kw('Machine learning'),
    kw('Neural network (machine learning)', 'neural network'),
    kw('Natural language processing'),
    kw('Computer vision'),
    kw('Expert system'),
    kw('Knowledge representation and reasoning'),
    kw('Reinforcement learning'),
    kw('Search algorithm'),
  ],
  'Machine learning': [
    kw('Supervised learning'),
    kw('Unsupervised learning'),
    kw('Neural network (machine learning)', 'neural network'),
    kw('Decision tree learning', 'decision tree'),
    kw('Overfitting'),
    kw('Gradient descent'),
    kw('Cross-validation (statistics)', 'cross-validation', 'cross validation'),
    kw('Feature (machine learning)', 'feature'),
  ],
  Biology: [
    kw('Cell (biology)', 'cell'),
    kw('Evolution'),
    kw('Genetics'),
    kw('Ecology'),
    kw('Organism'),
    kw('DNA', 'dna'),
    kw('Homeostasis'),
    kw('Taxonomy (biology)', 'taxonomy'),
  ],
  'Molecular biology': [
    kw('DNA', 'dna'),
    kw('RNA', 'rna'),
    kw('Protein'),
    kw('Gene expression'),
    kw('Transcription (biology)', 'transcription'),
    kw('Translation (biology)', 'translation'),
    kw('Polymerase chain reaction', 'pcr'),
    kw('Molecular cloning'),
  ],
  'Cell biology': [
    kw('Cell (biology)', 'cell'),
    kw('Organelle'),
    kw('Cell membrane'),
    kw('Mitochondrion'),
    kw('Mitosis'),
    kw('Meiosis'),
    kw('Cytoskeleton'),
    kw('Endoplasmic reticulum'),
  ],
  Microbiology: [
    kw('Bacteria'),
    kw('Virus'),
    kw('Fungus'),
    kw('Archaea'),
    kw('Pathogen'),
    kw('Antibiotic'),
    kw('Gram stain'),
    kw('Microbiological culture'),
  ],
  Biochemistry: [
    kw('Enzyme'),
    kw('Metabolism'),
    kw('Protein'),
    kw('Amino acid'),
    kw('Carbohydrate'),
    kw('Lipid'),
    kw('Adenosine triphosphate', 'atp'),
    kw('Glycolysis'),
  ],
  Biophysics: [
    kw('Protein structure'),
    kw('Membrane potential'),
    kw('Spectroscopy'),
    kw('Molecular dynamics'),
    kw('X-ray crystallography'),
    kw('Thermodynamics'),
    kw('Ion channel'),
    kw('Fluorescence'),
  ],
  Biotechnology: [
    kw('Genetic engineering'),
    kw('Recombinant DNA', 'recombinant dna'),
    kw('Fermentation'),
    kw('Bioreactor'),
    kw('Monoclonal antibody'),
    kw('CRISPR', 'crispr'),
    kw('Bioinformatics'),
    kw('Tissue engineering'),
  ],
  Genetics: [
    kw('Gene'),
    kw('DNA', 'dna'),
    kw('Chromosome'),
    kw('Allele'),
    kw('Heredity'),
    kw('Mutation'),
    kw('Mendelian inheritance'),
    kw('Genome'),
  ],
  Neuroscience: [
    kw('Neuron'),
    kw('Brain'),
    kw('Synapse'),
    kw('Neurotransmitter'),
    kw('Action potential'),
    kw('Central nervous system'),
    kw('Neuroplasticity'),
    kw('Cognition'),
  ],
  Chemistry: [
    kw('Atom'),
    kw('Chemical bond'),
    kw('Molecule'),
    kw('Periodic table'),
    kw('Chemical reaction'),
    kw('Stoichiometry'),
    kw('Acid–base reaction', 'acid base reaction', 'acid-base reaction'),
    kw('Organic chemistry'),
  ],
  Physics: [
    kw('Classical mechanics'),
    kw('Electromagnetism'),
    kw('Thermodynamics'),
    kw('Quantum mechanics'),
    kw('Theory of relativity', 'relativity'),
    kw('Energy'),
    kw('Force'),
    kw('Wave'),
  ],
  Mathematics: [
    kw('Algebra'),
    kw('Calculus'),
    kw('Geometry'),
    kw('Linear algebra'),
    kw('Mathematical proof'),
    kw('Number theory'),
    kw('Set theory'),
    kw('Trigonometry'),
  ],
  Statistics: [
    kw('Probability'),
    kw('Statistical hypothesis testing', 'hypothesis testing'),
    kw('Arithmetic mean', 'mean'),
    kw('Variance'),
    kw('Regression analysis'),
    kw('Sample (statistics)', 'sample'),
    kw('Confidence interval'),
    kw('Bayesian statistics'),
  ],
  Engineering: [
    kw('Engineering design process'),
    kw('Statics'),
    kw('Dynamics (mechanics)', 'dynamics'),
    kw('Materials science'),
    kw('Thermodynamics'),
    kw('Engineering drawing'),
    kw('Control system'),
    kw('Prototype'),
  ],
  'Mechanical engineering': [
    kw('Statics'),
    kw('Dynamics (mechanics)', 'dynamics'),
    kw('Fluid mechanics'),
    kw('Heat transfer'),
    kw('Simple machine'),
    kw('Manufacturing'),
    kw('Strength of materials'),
    kw('Thermodynamics'),
  ],
  'Electrical engineering': [
    kw('Electrical network', 'electric circuit', 'circuit'),
    kw("Ohm's law", 'ohms law', "ohm's law"),
    kw('Electromagnetism'),
    kw('Signal processing'),
    kw('Digital electronics'),
    kw('Control system'),
    kw('Semiconductor'),
    kw('Electric power'),
  ],
  'Civil engineering': [
    kw('Structural engineering'),
    kw('Geotechnical engineering'),
    kw('Transportation engineering'),
    kw('Hydraulics'),
    kw('Concrete'),
    kw('Surveying'),
    kw('Construction'),
    kw('Statics'),
  ],
  'Chemical engineering': [
    kw('Chemical reactor'),
    kw('Fluid mechanics'),
    kw('Heat transfer'),
    kw('Mass transfer'),
    kw('Thermodynamics'),
    kw('Process control'),
    kw('Distillation'),
    kw('Unit operation'),
  ],
  'Biomedical engineering': [
    kw('Biomechanics'),
    kw('Biomaterial'),
    kw('Medical imaging'),
    kw('Tissue engineering'),
    kw('Medical device'),
    kw('Physiology'),
    kw('Signal processing'),
    kw('Prosthesis'),
  ],
  'Industrial engineering': [
    kw('Operations research'),
    kw('Quality control'),
    kw('Supply chain'),
    kw('Ergonomics'),
    kw('Lean manufacturing'),
    kw('Six Sigma', 'six sigma'),
    kw('Production planning'),
    kw('Systems engineering'),
  ],
  'Aerospace engineering': [
    kw('Aerodynamics'),
    kw('Flight dynamics (fixed-wing aircraft)', 'flight dynamics'),
    kw('Jet engine'),
    kw('Aircraft'),
    kw('Spacecraft'),
    kw('Fluid mechanics'),
    kw('Avionics'),
    kw('Orbital mechanics'),
  ],
  Medicine: [
    kw('Medical diagnosis', 'diagnosis'),
    kw('Pathology'),
    kw('Pharmacology'),
    kw('Anatomy'),
    kw('Physiology'),
    kw('Internal medicine'),
    kw('Surgery'),
    kw('Medical ethics'),
  ],
  Nursing: [
    kw('Nursing assessment'),
    kw('Vital signs'),
    kw('Patient safety'),
    kw('Nursing process'),
    kw('Pharmacology'),
    kw('Infection control'),
    kw('Health assessment'),
    kw('Nursing care plan'),
  ],
  Dentistry: [
    kw('Tooth'),
    kw('Tooth decay', 'dental caries'),
    kw('Periodontology'),
    kw('Orthodontics'),
    kw('Endodontics'),
    kw('Dental restoration'),
    kw('Oral hygiene'),
    kw('Oral and maxillofacial surgery'),
  ],
  'Public health': [
    kw('Epidemiology'),
    kw('Biostatistics'),
    kw('Health policy'),
    kw('Environmental health'),
    kw('Health promotion'),
    kw('Vaccination'),
    kw('Disease surveillance'),
    kw('Social determinants of health'),
  ],
  Psychology: [
    kw('Cognition'),
    kw('Behavior'),
    kw('Memory'),
    kw('Learning'),
    kw('Personality psychology'),
    kw('Developmental psychology'),
    kw('Psychometrics'),
    kw('Mental disorder'),
  ],
  Sociology: [
    kw('Social structure'),
    kw('Socialization'),
    kw('Culture'),
    kw('Social stratification'),
    kw('Social institution'),
    kw('Deviance (sociology)', 'deviance'),
    kw('Social research'),
    kw('Demography'),
  ],
  Anthropology: [
    kw('Culture'),
    kw('Ethnography'),
    kw('Archaeology'),
    kw('Linguistic anthropology'),
    kw('Biological anthropology'),
    kw('Kinship'),
    kw('Cultural relativism'),
    kw('Field research'),
  ],
  Economics: [
    kw('Supply and demand'),
    kw('Microeconomics'),
    kw('Macroeconomics'),
    kw('Market (economics)', 'market'),
    kw('Inflation'),
    kw('Gross domestic product', 'gdp'),
    kw('Opportunity cost'),
    kw('Elasticity (economics)', 'elasticity'),
  ],
  'Political science': [
    kw('Government'),
    kw('Democracy'),
    kw('Political philosophy'),
    kw('International relations'),
    kw('Public policy'),
    kw('Comparative politics'),
    kw('Election'),
    kw('Sovereignty'),
  ],
  'Business administration': [
    kw('Management'),
    kw('Organizational behavior'),
    kw('Strategic management'),
    kw('Marketing'),
    kw('Accounting'),
    kw('Operations management'),
    kw('Leadership'),
    kw('Business ethics'),
  ],
  Accounting: [
    kw('Financial statement'),
    kw('Balance sheet'),
    kw('Income statement'),
    kw('Generally accepted accounting principles', 'gaap'),
    kw('Audit'),
    kw('Bookkeeping'),
    kw('Debits and credits'),
    kw('Management accounting', 'managerial accounting'),
  ],
  Finance: [
    kw('Time value of money'),
    kw('Interest rate'),
    kw('Investment'),
    kw('Share (finance)', 'stock'),
    kw('Bond (finance)', 'bond'),
    kw('Financial risk'),
    kw('Financial market'),
    kw('Corporate finance'),
  ],
  Marketing: [
    kw('Market segmentation'),
    kw('Brand'),
    kw('Advertising'),
    kw('Consumer behaviour', 'consumer behavior'),
    kw('Marketing mix'),
    kw('Pricing'),
    kw('Digital marketing'),
    kw('Market research'),
  ],
  Architecture: [
    kw('Architectural design'),
    kw('Building'),
    kw('Structural engineering'),
    kw('Architectural drawing'),
    kw('Urban planning'),
    kw('Construction'),
    kw('Architectural style'),
    kw('Sustainable architecture'),
  ],
  Education: [
    kw('Pedagogy'),
    kw('Curriculum'),
    kw('Learning'),
    kw('Educational psychology'),
    kw('Lesson plan'),
    kw('Educational assessment'),
    kw('Classroom'),
    kw('Teaching method'),
  ],
  Journalism: [
    kw('News'),
    kw('News style'),
    kw('Fact-checking', 'fact checking'),
    kw('Source (journalism)', 'source'),
    kw('Copy editing'),
    kw('Journalism ethics and standards'),
    kw('Investigative journalism'),
    kw('Newsroom', 'interview'),
  ],
  Linguistics: [
    kw('Phonetics'),
    kw('Phonology'),
    kw('Morphology (linguistics)', 'morphology'),
    kw('Syntax'),
    kw('Semantics'),
    kw('Grammar'),
    kw('Language'),
    kw('Sociolinguistics'),
  ],
  Philosophy: [
    kw('Ethics'),
    kw('Epistemology'),
    kw('Metaphysics'),
    kw('Logic'),
    kw('Political philosophy'),
    kw('Aesthetics'),
    kw('Argument'),
    kw('Critical thinking'),
  ],
  History: [
    kw('Primary source'),
    kw('Historiography'),
    kw('Chronology'),
    kw('Civilization'),
    kw('Archive'),
    kw('Historical method'),
    kw('Periodization'),
    kw('Oral history'),
  ],
  'Environmental science': [
    kw('Ecosystem'),
    kw('Pollution'),
    kw('Climate change'),
    kw('Biodiversity'),
    kw('Sustainability'),
    kw('Environmental policy'),
    kw('Conservation biology'),
    kw('Ecology'),
  ],
  'Earth science': [
    kw('Geology'),
    kw('Meteorology'),
    kw('Oceanography'),
    kw('Plate tectonics'),
    kw('Rock (geology)', 'rock'),
    kw('Atmosphere of Earth', 'atmosphere'),
    kw('Hydrology'),
    kw('Mineral'),
  ],
  Astronomy: [
    kw('Star'),
    kw('Planet'),
    kw('Galaxy'),
    kw('Solar System', 'solar system'),
    kw('Telescope'),
    kw('Orbit'),
    kw('Universe'),
    kw('Light-year', 'light year'),
  ],
  Geology: [
    kw('Rock (geology)', 'rock'),
    kw('Mineral'),
    kw('Plate tectonics'),
    kw('Volcano'),
    kw('Earthquake'),
    kw('Sedimentary rock'),
    kw('Fossil'),
    kw('Geologic time scale'),
  ],
});
